apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: app-service-rules
  name: app-service-rules
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-service-rules
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: app-service-rules
    spec:
      containers:
        - env:
            - name: BINDING_PUBLISHTOPIC
              value: events
            - name: CLIENTS_COMMAND_HOST
              value: edgex-core-command
            - name: CLIENTS_COREDATA_HOST
              value: edgex-core-data
            - name: CLIENTS_DATA_HOST
              value: edgex-core-data
            - name: CLIENTS_METADATA_HOST
              value: edgex-core-metadata
            - name: CLIENTS_NOTIFICATIONS_HOST
              value: edgex-support-notifications
            - name: CLIENTS_RULESENGINE_HOST
              value: edgex-kuiper
            - name: CLIENTS_SCHEDULER_HOST
              value: edgex-support-scheduler
            - name: CLIENTS_VIRTUALDEVICE_HOST
              value: edgex-device-virtual
            - name: DATABASES_PRIMARY_HOST
              value: edgex-redis
            - name: EDGEX_PROFILE
              value: rules-engine
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: MESSAGEBUS_SUBSCRIBEHOST_HOST
              value: edgex-core-data
            - name: REGISTRY_HOST
              value: edgex-core-consul
            - name: SERVICE_HOST
              value: edgex-app-service-configurable-rules
            - name: SERVICE_PORT
              value: "48100"
          image: edgexfoundry/docker-app-service-configurable:1.3.0
          name: edgex-app-service-configurable-rules
          ports:
            - containerPort: 48100
          resources: {}
      hostname: edgex-app-service-configurable-rules
      restartPolicy: Always
status: {}
