apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: command
  name: command
spec:
  ports:
    - name: "48082"
      port: 48082
      targetPort: 48082
  selector:
    io.kompose.service: command
status:
  loadBalancer: {}
