apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: consul
    spec:
      containers:
        - env:
            - name: EDGEX_DB
              value: redis
            - name: EDGEX_SECURE
              value: "true"
            - name: SECRETSTORE_SETUP_DONE_FLAG
              value: /tmp/edgex/secrets/edgex-consul/.secretstore-setup-done
          image: edgexfoundry/docker-edgex-consul:1.3.0
          name: edgex-core-consul
          ports:
            - containerPort: 8500
          resources: {}
          volumeMounts:
            - mountPath: /consul/config
              name: consul-config
            - mountPath: /consul/data
              name: consul-data
            - mountPath: /consul/scripts
              name: consul-scripts
            - mountPath: /tmp/edgex/secrets/ca
              name: consul-claim3
              readOnly: true
            - mountPath: /tmp/edgex/secrets/edgex-consul
              name: consul-claim4
              readOnly: true
            - mountPath: /tmp/edgex/secrets/edgex-kong
              name: consul-claim5
              readOnly: true
            - mountPath: /tmp/edgex/secrets/edgex-vault
              name: consul-claim6
              readOnly: true
      hostname: edgex-core-consul
      restartPolicy: Always
      volumes:
        - name: consul-config
          persistentVolumeClaim:
            claimName: consul-config
        - name: consul-data
          persistentVolumeClaim:
            claimName: consul-data
        - name: consul-scripts
          persistentVolumeClaim:
            claimName: consul-scripts
        - name: consul-claim3
          persistentVolumeClaim:
            claimName: consul-claim3
            readOnly: true
        - name: consul-claim4
          persistentVolumeClaim:
            claimName: consul-claim4
            readOnly: true
        - name: consul-claim5
          persistentVolumeClaim:
            claimName: consul-claim5
            readOnly: true
        - name: consul-claim6
          persistentVolumeClaim:
            claimName: consul-claim6
            readOnly: true
status: {}
