apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: device-virtual
  name: device-virtual
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: device-virtual
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: device-virtual
    spec:
      containers:
        - env:
            - name: CLIENTS_COMMAND_HOST
              value: edgex-core-command
            - name: CLIENTS_COREDATA_HOST
              value: edgex-core-data
            - name: CLIENTS_DATA_HOST
              value: edgex-core-data
            - name: CLIENTS_METADATA_HOST
              value: edgex-core-metadata
            - name: CLIENTS_NOTIFICATIONS_HOST
              value: edgex-support-notifications
            - name: CLIENTS_RULESENGINE_HOST
              value: edgex-kuiper
            - name: CLIENTS_SCHEDULER_HOST
              value: edgex-support-scheduler
            - name: CLIENTS_VIRTUALDEVICE_HOST
              value: edgex-device-virtual
            - name: DATABASES_PRIMARY_HOST
              value: edgex-redis
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: REGISTRY_HOST
              value: edgex-core-consul
            - name: SERVICE_HOST
              value: edgex-device-virtual
          image: edgexfoundry/docker-device-virtual-go:1.3.0
          name: edgex-device-virtual
          ports:
            - containerPort: 49990
          resources: {}
      hostname: edgex-device-virtual
      restartPolicy: Always
status: {}
