apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: kong-db
  name: kong-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: kong-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_USER
              value: kong
          image: postgres:12.3-alpine
          name: kong-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /var/run
              name: kong-db-tmpfs0
            - mountPath: /tmp
              name: kong-db-tmpfs1
            - mountPath: /run
              name: kong-db-tmpfs2
      hostname: kong-db
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - emptyDir:
            medium: Memory
          name: kong-db-tmpfs0
        - emptyDir:
            medium: Memory
          name: kong-db-tmpfs1
        - emptyDir:
            medium: Memory
          name: kong-db-tmpfs2
status: {}
