apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: security-secrets-setup
  name: security-secrets-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: security-secrets-setup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: security-secrets-setup
    spec:
      containers:
        - args:
            - generate
          image: edgexfoundry/docker-security-secrets-setup-go:1.3.0
          name: edgex-secrets-setup
          resources: {}
          volumeMounts:
            - mountPath: /etc/edgex/pki
              name: secrets-setup-cache
            - mountPath: /tmp/edgex/secrets
              name: security-secrets-setup-claim1
            - mountPath: /vault/init
              name: vault-init
            - mountPath: /tmp
              name: security-secrets-setup-tmpfs0
            - mountPath: /run
              name: security-secrets-setup-tmpfs1
      hostname: edgex-secrets-setup
      restartPolicy: Always
      volumes:
        - name: secrets-setup-cache
          persistentVolumeClaim:
            claimName: secrets-setup-cache
        - name: security-secrets-setup-claim1
          persistentVolumeClaim:
            claimName: security-secrets-setup-claim1
        - name: vault-init
          persistentVolumeClaim:
            claimName: vault-init
        - emptyDir:
            medium: Memory
          name: security-secrets-setup-tmpfs0
        - emptyDir:
            medium: Memory
          name: security-secrets-setup-tmpfs1
status: {}
