apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vault
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: vault
    spec:
      containers:
        - command:
            - /vault/init/start_vault.sh
          env:
            - name: VAULT_ADDR
              value: https://edgex-vault:8200
            - name: VAULT_CONFIG_DIR
              value: /vault/config
            - name: VAULT_UI
              value: "true"
          image: vault:1.5.3
          name: edgex-vault
          ports:
            - containerPort: 8200
          resources: {}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /tmp/edgex/secrets/edgex-vault
              name: vault-claim0
              readOnly: true
            - mountPath: /vault/file
              name: vault-file
            - mountPath: /vault/init
              name: vault-init
              readOnly: true
            - mountPath: /vault/logs
              name: vault-logs
            - mountPath: /vault/config
              name: vault-tmpfs0
      hostname: edgex-vault
      restartPolicy: Always
      volumes:
        - name: vault-claim0
          persistentVolumeClaim:
            claimName: vault-claim0
            readOnly: true
        - name: vault-file
          persistentVolumeClaim:
            claimName: vault-file
        - name: vault-init
          persistentVolumeClaim:
            claimName: vault-init
            readOnly: true
        - name: vault-logs
          persistentVolumeClaim:
            claimName: vault-logs
        - emptyDir:
            medium: Memory
          name: vault-tmpfs0
status: {}
