apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: vault-worker
  name: vault-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vault-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: vault-worker
    spec:
      containers:
        - env:
            - name: SECRETSTORE_SETUP_DONE_FLAG
              value: /tmp/edgex/secrets/edgex-consul/.secretstore-setup-done
          image: edgexfoundry/docker-security-secretstore-setup-go:1.3.0
          name: edgex-vault-worker
          resources: {}
          volumeMounts:
            - mountPath: /consul/scripts
              name: consul-scripts
              readOnly: true
            - mountPath: /tmp/edgex/secrets
              name: vault-worker-claim1
            - mountPath: /vault/config
              name: vault-config
            - mountPath: /run
              name: vault-worker-tmpfs0
            - mountPath: /vault
              name: vault-worker-tmpfs1
      hostname: edgex-vault-worker
      restartPolicy: Always
      volumes:
        - name: consul-scripts
          persistentVolumeClaim:
            claimName: consul-scripts
            readOnly: true
        - name: vault-worker-claim1
          persistentVolumeClaim:
            claimName: vault-worker-claim1
        - name: vault-config
          persistentVolumeClaim:
            claimName: vault-config
        - emptyDir:
            medium: Memory
          name: vault-worker-tmpfs0
        - emptyDir:
            medium: Memory
          name: vault-worker-tmpfs1
status: {}
